name: stock-saas-api
services:
- name: api
  source_dir: /
  github:
    repo: chuma-beep/stock-saas
    branch: main
  dockerfile_path: Dockerfile
  environment_slug: go
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
  - key: ALPHA_VANTAGE_API_KEY
    scope: RUN_AND_BUILD_TIME
  - key: GROQ_API_KEY
    scope: RUN_AND_BUILD_TIME
  health_check:
    http_path: /health
